-- Write an SQL query to fetch worker names with salaries >= 50000 and <= 100000.

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME)AS WORKER_NAME,SALARY FROM WorkerDetails WHERE WORKER_ID IN (SELECT WORKER_ID FROM WorkerDetails WHERE SALARY BETWEEN 50000 AND 100000)